- name: sites-enabled directory is present
  file:
    path=/etc/nginx/sites-enabled
    state=directory
  tags: [nginx]

- name: certs-enabled directory is present
  file:
    path=/etc/nginx/certs-enabled
    state=directory
  tags: [nginx]

- name: log directory is present
  file:
    path=/var/log/nginx
    state=directory
  tags: [nginx]

- name: nginx container is running
  docker_container:
    image: "dockerfile/nginx"
    name: "nginx"
    state: "started"
    ports: "80:80"
    restart: yes
    restart_policy: always
    volumes: "{{ volumes }}"
  tags: [nginx]
  ignore_errors: yes